### PR TITLE
Update index.css

### PR DESCRIPTION
**Pull request by petr-kastovsky**
I assume that the index.css in Starter should not contain the CSS code similar to all other projects in the tutorial.

### CODE REVIEW

**Comment by john-smilga** [comment]
I believe I explained the CSS setup in detail during the videos.

**Comment by petr-kastovsky** [comment]
Hmm, I must have missed it but I've been following all the videos pretty closely. To those who don't want to work on the CSS you provide the CSS in the README.md with an instruction to copy that into the index.css so having all that code there already wasn't expected.

**Comment by john-smilga** [comment]
Yes, that's true, but I'm pretty sure I mentioned during the introduction of this project that it contains more complex CSS. Also, the main logic won't work without CSS, so in this case, I provided more CSS code

**Comment by petr-kastovsky** [comment]
Indeed, It does contain more complex CSS, thanks for all the effort you've put into building this.

**Comment by john-smilga** [comment]
👍

**Pull request closed without merging**
